### ISSUE TITLE
jmx-cli hangs if no tty is available

### ISSUE THREAD

**Issue by alexsuter** [weissreto/jmx-cli#1]
If I use jmx-cli without a tty, in my headless build environment, there seems to be a problem. The application just hangs:

```
locadmin@ZugProBldDocker02:~$ docker exec ivy-visualvm_ivy_1 /opt/ivy/jmx-cli-0.1.0/bin/jmcli list beans

^[[39;1R
```

The jmcli prints `^[[39;1R` and hangs afterwards. Maybe there is a problem with the color output? If I have time, i will further analyze this problem.

**Comment by weissreto** [comment]
Hi Alex

That could be. The jmcli will ask the tty about the window size. And if no tty is available there is also no windows size and therefore no answer from tty. I think jmcli will wait forever for the answer.

Regards

Reto Weiss
Product Owner / Software Developer

AXON iVY
digitalize your business

AXON Ivy AG
Schlössli Schönegg ∙ Wilhelmshöhe ∙ CH-6003 Luzern
ivyTeam: Baarerstrasse 12 ∙ CH-6300 Zug
direkt: +41 (41) 726 07 82 ∙ office: +41 (41) 249 25 70
email: reto.weiss@axonivy.com<mailto:reto.weiss@axonivy.com> ∙ skype: retoweiss72 ∙ web: www.axonivy.com<http://www.axonivy.com/>

Diese Brands gehören zu AXON Ivy:

AXON iVY
digitalize your business

AXON FiNTECH
boost your business

AXON iNSURTECH
boost your business


SCHWEIZ ∙ ÖSTERREICH ∙ DEUTSCHLAND ∙ FRANKREICH ∙ SINGAPUR ∙ HONG KONG ∙ GROSSBRITANIEN ∙ USA ∙ VIETNAM

Folgen Sie uns auf Twitter<https://twitter.com/axonivy>  ∙  Facebook<https://de-de.facebook.com/axonivy/>  ∙  LinkedIn<https://www.linkedin.com/company-beta/9181790/>  ∙  Xing<https://www.xing.com/companies/axonivyag>  ∙  Youtube<https://www.youtube.com/channel/UCkoNcDoeDAVM7FB-txy3jnQ>

Von: Alex <notifications@github.com>
Gesendet: Dienstag, 16. Oktober 2018 07:33
An: weissreto/jmx-cli <jmx-cli@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [weissreto/jmx-cli] Problems if no tty is available (#1)


If I use jmx-cli without a tty, in my headless build environment, there seems to be a problem. The application just hangs:

locadmin@ZugProBldDocker02:~$ docker exec ivy-visualvm_ivy_1 /opt/ivy/jmx-cli-0.1.0/bin/jmcli list beans



^[[39;1R

The jmcli prints ^[[39;1R and hangs afterwards. Maybe there is a problem with the color output? If I have time, i will further analyze this problem.
